name: 0.1$(Rev:.r)

trigger:
- main

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vsix: '$(Build.ArtifactStagingDirectory)/vsix/azure-pipelines-ensure-tests-task-$(Build.BuildNumber).vsix'
  zip: '$(Build.ArtifactStagingDirectory)/zip/azure-pipelines-ensure-tests-task-$(Build.BuildNumber).zip'
  marketplaceServiceConnection: '24325a98-0d4b-4180-9936-c930a4156258' 

steps:
- task: TfxInstaller@4
  inputs:
    version: 'v0.x'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(zip)'
    replaceExistingArchive: true

- task: PackageAzureDevOpsExtension@4
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(vsix)'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: false

- task: AzureCLI@2
  displayName: 'Authenticate with Service Principal'
  inputs:
    azureSubscription: 'azure-devops-marketplace'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    useGlobalConfig: true
    inlineScript: |
      $accessToken = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query "accessToken" --output tsv
      write-host "##vso[task.setsecret]$accessToken"
      write-host "##vso[task.setendpoint id=$env:MARKETPLACESERVICECONNECTION;field=authParameter;key=password]$accessToken"

- task: PublishAzureDevOpsExtension@4
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: $(marketplaceServiceConnection)
    fileType: 'vsix'
    vsixFile: '$(vsix)'
    updateTasksVersion: false
    noWaitValidation: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'Output'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHub - jessehouwing'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildNumber)'
    title: '$(Build.BuildNumber)'
    releaseNotesSource: 'inline'
    assets: '$(Build.ArtifactStagingDirectory)/zip/*'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
